### ISSUE TITLE
UseHttps error

### ISSUE THREAD

**Issue by CypherPotato** [PeteX/StandaloneKestrel#3]
When trying to call `UseHttps` on `KestrelServerOptions.Listen` I got this exception:

> System.ArgumentNullException: 'Value cannot be null. Arg_ParamName_Name'

Also I'm specifying an valid self signed cert with it's password. Any ideas to handle this exception and make Kestrel listen on https?

**Comment by PeteX** [comment]
I never tried that, so I don't know why it doesn't work.  If you figure it out, let me know and I'll include it in the repository!

The source code for Kestrel is [here](https://github.com/dotnet/aspnetcore/tree/main/src/Servers/Kestrel) (and the source code for `KestrelServerOptions` specifically is [here](https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs)).  I would start by looking at the backtrace you presumably get along with the exception, and tying it up with the source code.  It's probably that something doesn't get initialised when running Kestrel in this way.

With earlier versions of .NET I had a lot of problems where there was something uninitialised, but there was no public API for doing it.  That's become easier with more recent editions, hopefully that will be true for the https issue too.

**Comment by CypherPotato** [comment]
I think it is being reused cause `serverOptions.ApplicationServices` is null when trying to call `UseHttps()`. I tried to create a ServiceCollection, but it is instanced empty and doesn't work. I don't want to depend on aspnet to create an application service.

**Comment by PeteX** [comment]
I got curious about this, and did my own investigation.  It looks as though you're not the only one to have been bitten by this problem—see for example dotnet/aspnetcore#31561.  `UseHttps` seems to expect an `ILoggerFactory` to have been registered, and it throws if there isn't one.

Fortunately, it's easy to create your own class which implements `IServiceProvider`.  Instead of having a full DI system, you can just hard-code specific classes that you want to return.  I expect this technique will be useful for people who want to do more with standalone Kestrel.  It's likely that other services will depend on classes being registered with the DI system, and this provides a way to keep them happy.
